/**
 * @file hpatch_impl.c
 * @brief CI HPatchLite shim that exercises the production QBoot HPatch path.
 *
 * @details The shim implements deterministic HPatchLite fixture coverage
 * generated by the QBoot package-tool tests, including uncompressed and
 * TinyUZ-compressed bodies, single-cover and multi-cover restore paths, and
 * malformed patch rejection cases. It is intentionally small, but it runs
 * through algorithm/qboot_hpatchlite.c instead of the host adapter so CI cannot
 * silently skip the production integration path.
 */
#include "hpatch_impl.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define HPATCH_CI_MAGIC_H       0x68u /**< HPatchLite 'h' magic byte. */
#define HPATCH_CI_MAGIC_I       0x49u /**< HPatchLite 'I' magic byte. */
#define HPATCH_CI_COMPRESS_NONE 0u    /**< No-compression fixture selector. */
#define HPATCH_CI_COMPRESS_TUZ  1u    /**< TinyUZ-compressed fixture selector. */
#define HPATCH_CI_VERSION       1u    /**< Fixture format version. */
#define HPATCH_CI_READ_CHUNK    256u  /**< Patch stream read growth unit. */
#define HPATCH_CI_TUZ_DICT_SIZE_SAVED_BYTES 4u    /**< TinyUZ dictionary size header length. */
#define HPATCH_CI_TUZ_MIN_LITERAL_LEN       15u   /**< TinyUZ literal-line base length. */
#define HPATCH_CI_TUZ_MIN_DICT_MATCH_LEN    2u    /**< TinyUZ dictionary match base length. */
#define HPATCH_CI_TUZ_BIG_POS_FOR_LEN       2688u /**< TinyUZ large-position length threshold. */

/** @brief TinyUZ bit-stream reader state. */
typedef struct
{
    const hpi_byte *data; /**< Compressed TinyUZ stream buffer. */
    hpi_size_t len;       /**< Compressed stream length in bytes. */
    hpi_size_t off;       /**< Current byte-stream offset. */
    uint32_t types;       /**< Cached low-to-high type bits. */
    uint32_t type_count;  /**< Number of cached type bits. */
} hpatch_ci_tuz_reader_t;

/**
 * @brief Read the complete HPatchLite stream from the production callback.
 *
 * @param read_diff Stream read callback.
 * @param input_stream Stream callback context.
 * @param data         Output heap buffer containing the whole stream.
 * @param size      Output stream size in bytes.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_read_all(hpi_TInputStream_read read_diff,
                                   hpi_TInputStreamHandle input_stream,
                                   hpi_byte **data,
                                   hpi_size_t *size)
{
    hpi_byte *buf = NULL;
    hpi_size_t len = 0u;
    hpi_size_t cap = 0u;

    if (read_diff == NULL || data == NULL || size == NULL)
    {
        return hpi_FALSE;
    }

    for (;;)
    {
        hpi_size_t request = HPATCH_CI_READ_CHUNK;
        hpi_byte chunk[HPATCH_CI_READ_CHUNK];
        if (!read_diff(input_stream, chunk, &request))
        {
            free(buf);
            return hpi_FALSE;
        }
        if (request == 0u)
        {
            break;
        }
        if (len + request < len)
        {
            free(buf);
            return hpi_FALSE;
        }
        if (len + request > cap)
        {
            hpi_size_t next = cap == 0u ? HPATCH_CI_READ_CHUNK : cap;
            hpi_byte *new_buf;
            while (next < len + request)
            {
                if (next > ((hpi_size_t)-1) / 2u)
                {
                    free(buf);
                    return hpi_FALSE;
                }
                next *= 2u;
            }
            new_buf = (hpi_byte *)realloc(buf, next);
            if (new_buf == NULL)
            {
                free(buf);
                return hpi_FALSE;
            }
            buf = new_buf;
            cap = next;
        }
        memcpy(buf + len, chunk, request);
        len += request;
    }

    *data = buf;
    *size = len;
    return hpi_TRUE;
}

/**
 * @brief Read little-endian integer bytes from a patch buffer.
 *
 * @param data       Patch buffer.
 * @param len        Patch buffer length.
 * @param off        In/out read offset.
 * @param byte_count Number of little-endian bytes to consume.
 * @param out        Output integer value.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_read_le_size(const hpi_byte *data, hpi_size_t len,
                                       hpi_size_t *off, hpi_size_t byte_count,
                                       uint32_t *out)
{
    uint32_t value = 0u;

    if (data == NULL || off == NULL || out == NULL || byte_count > sizeof(uint32_t) ||
        *off > len || byte_count > (len - *off))
    {
        return hpi_FALSE;
    }
    for (hpi_size_t i = 0u; i < byte_count; i++)
    {
        value |= ((uint32_t)data[*off + i]) << (8u * i);
    }
    *off += byte_count;
    *out = value;
    return hpi_TRUE;
}

/**
 * @brief Read HPatchLite variable-length unsigned integer encoding.
 *
 * @param data     Patch buffer.
 * @param len      Patch buffer length.
 * @param off      In/out read offset.
 * @param initial  Initial low-bit value from the tag byte.
 * @param has_next Whether more bytes are present.
 * @param out      Output integer value.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_read_var_uint(const hpi_byte *data, hpi_size_t len,
                                        hpi_size_t *off, uint32_t initial,
                                        hpi_BOOL has_next, uint32_t *out)
{
    uint32_t value = initial;

    if (data == NULL || off == NULL || out == NULL || *off > len)
    {
        return hpi_FALSE;
    }

    while (has_next)
    {
        hpi_byte code;
        if (*off >= len)
        {
            return hpi_FALSE;
        }
        code = data[*off];
        *off += 1u;
        if (value > (UINT32_MAX >> 7u))
        {
            return hpi_FALSE;
        }
        value = (value << 7u) | (uint32_t)(code & 0x7Fu);
        has_next = (code >> 7u) != 0u ? hpi_TRUE : hpi_FALSE;
    }
    *out = value;
    return hpi_TRUE;
}

/**
 * @brief Read one byte from a TinyUZ stream.
 *
 * @param reader TinyUZ reader state.
 * @param out    Output byte.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_tuz_read_byte(hpatch_ci_tuz_reader_t *reader,
                                        hpi_byte *out)
{
    if (reader == NULL || out == NULL || reader->off >= reader->len)
    {
        return hpi_FALSE;
    }
    *out = reader->data[reader->off++];
    return hpi_TRUE;
}

/**
 * @brief Read low-to-high TinyUZ type bits.
 *
 * @param reader    TinyUZ reader state.
 * @param bit_count Number of bits to read, up to 8.
 * @param out       Output bit field.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_tuz_read_lowbits(hpatch_ci_tuz_reader_t *reader,
                                           uint32_t bit_count, uint32_t *out)
{
    uint32_t count;
    uint32_t result;
    hpi_byte value;

    if (reader == NULL || out == NULL || bit_count == 0u || bit_count > 8u ||
        reader->type_count > 8u)
    {
        return hpi_FALSE;
    }

    count = reader->type_count;
    result = reader->types;
    if (count >= bit_count)
    {
        reader->type_count = count - bit_count;
        reader->types = result >> bit_count;
        *out = result & ((1u << bit_count) - 1u);
        return hpi_TRUE;
    }

    if (!hpatch_ci_tuz_read_byte(reader, &value))
    {
        return hpi_FALSE;
    }
    bit_count -= count;
    reader->type_count = 8u - bit_count;
    reader->types = ((uint32_t)value) >> bit_count;
    *out = (result | (((uint32_t)value) << count)) &
           ((1u << (bit_count + count)) - 1u);
    return hpi_TRUE;
}

/**
 * @brief Decode a TinyUZ variable-length integer.
 *
 * @param reader   TinyUZ reader state.
 * @param read_bit Packed bit width.
 * @param out      Output integer value.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_tuz_unpack_len(hpatch_ci_tuz_reader_t *reader,
                                         uint32_t read_bit, uint32_t *out)
{
    uint32_t value = 0u;

    if (reader == NULL || out == NULL || read_bit < 2u || read_bit > 8u)
    {
        return hpi_FALSE;
    }

    for (;;)
    {
        uint32_t lowbit;
        uint32_t payload_mask = (1u << (read_bit - 1u)) - 1u;
        if (!hpatch_ci_tuz_read_lowbits(reader, read_bit, &lowbit) ||
            value > (UINT32_MAX >> (read_bit - 1u)))
        {
            return hpi_FALSE;
        }
        value = (value << (read_bit - 1u)) + (lowbit & payload_mask);
        if ((lowbit & (1u << (read_bit - 1u))) == 0u)
        {
            *out = value;
            return hpi_TRUE;
        }
        if (value == UINT32_MAX)
        {
            return hpi_FALSE;
        }
        value += 1u;
    }
}

/**
 * @brief Decode a TinyUZ dictionary/control position.
 *
 * @param reader TinyUZ reader state.
 * @param out    Output dictionary/control position.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_tuz_unpack_dict_pos(hpatch_ci_tuz_reader_t *reader,
                                              uint32_t *out)
{
    hpi_byte first;
    uint32_t high;

    if (!hpatch_ci_tuz_read_byte(reader, &first))
    {
        return hpi_FALSE;
    }
    if (first < (1u << 7u))
    {
        *out = first;
        return hpi_TRUE;
    }
    if (!hpatch_ci_tuz_unpack_len(reader, 3u, &high) || high > (UINT32_MAX >> 7u))
    {
        return hpi_FALSE;
    }
    *out = ((uint32_t)(first & 0x7Fu) | (high << 7u)) + (1u << 7u);
    return *out >= (1u << 7u) ? hpi_TRUE : hpi_FALSE;
}

/**
 * @brief Decompress a TinyUZ patch body into an uncompressed patch body.
 *
 * @param input         TinyUZ-compressed patch body.
 * @param input_len     TinyUZ-compressed patch body length.
 * @param expected_size Expected decompressed size.
 * @param output        Output heap buffer.
 * @param output_len    Output decompressed size.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_tuz_decompress(const hpi_byte *input, hpi_size_t input_len,
                                         uint32_t expected_size, hpi_byte **output,
                                         hpi_size_t *output_len)
{
    hpatch_ci_tuz_reader_t reader;
    hpi_byte *buf;
    hpi_size_t len = 0u;
    uint32_t dict_pos_back = 1u;
    hpi_BOOL is_have_data_back = hpi_FALSE;

    if (input == NULL || output == NULL || output_len == NULL ||
        input_len < HPATCH_CI_TUZ_DICT_SIZE_SAVED_BYTES ||
        (input[0] | input[1] | input[2] | input[3]) == 0u)
    {
        return hpi_FALSE;
    }

    buf = (hpi_byte *)malloc(expected_size == 0u ? 1u : expected_size);
    if (buf == NULL)
    {
        return hpi_FALSE;
    }

    reader.data = input;
    reader.len = input_len;
    reader.off = HPATCH_CI_TUZ_DICT_SIZE_SAVED_BYTES;
    reader.types = 0u;
    reader.type_count = 0u;

    for (;;)
    {
        uint32_t bit;
        if (!hpatch_ci_tuz_read_lowbits(&reader, 1u, &bit))
        {
            free(buf);
            return hpi_FALSE;
        }
        if ((bit & 1u) == 0u)
        {
            uint32_t saved_len;
            uint32_t saved_dict_pos;
            if (!hpatch_ci_tuz_unpack_len(&reader, 2u, &saved_len))
            {
                free(buf);
                return hpi_FALSE;
            }
            if (is_have_data_back)
            {
                if (!hpatch_ci_tuz_read_lowbits(&reader, 1u, &bit))
                {
                    free(buf);
                    return hpi_FALSE;
                }
                if (bit != 0u)
                {
                    saved_dict_pos = dict_pos_back;
                }
                else if (!hpatch_ci_tuz_unpack_dict_pos(&reader, &saved_dict_pos))
                {
                    free(buf);
                    return hpi_FALSE;
                }
            }
            else if (!hpatch_ci_tuz_unpack_dict_pos(&reader, &saved_dict_pos))
            {
                free(buf);
                return hpi_FALSE;
            }
            if (saved_dict_pos > HPATCH_CI_TUZ_BIG_POS_FOR_LEN)
            {
                if (saved_len == UINT32_MAX)
                {
                    free(buf);
                    return hpi_FALSE;
                }
                saved_len += 1u;
            }
            is_have_data_back = hpi_FALSE;
            if (saved_dict_pos != 0u)
            {
                uint32_t copy_len = saved_len + HPATCH_CI_TUZ_MIN_DICT_MATCH_LEN;
                if (copy_len < saved_len || saved_dict_pos > len ||
                    (hpi_size_t)copy_len > (hpi_size_t)expected_size - len)
                {
                    free(buf);
                    return hpi_FALSE;
                }
                dict_pos_back = saved_dict_pos;
                for (uint32_t i = 0u; i < copy_len; i++)
                {
                    buf[len] = buf[len - saved_dict_pos];
                    len += 1u;
                }
            }
            else
            {
                if (saved_len == 1u)
                {
                    uint32_t literal_extra;
                    uint32_t literal_len;
                    if (!hpatch_ci_tuz_unpack_len(&reader, 3u, &literal_extra) ||
                        literal_extra > UINT32_MAX - HPATCH_CI_TUZ_MIN_LITERAL_LEN)
                    {
                        free(buf);
                        return hpi_FALSE;
                    }
                    literal_len = literal_extra + HPATCH_CI_TUZ_MIN_LITERAL_LEN;
                    if ((hpi_size_t)literal_len > reader.len - reader.off ||
                        (hpi_size_t)literal_len > (hpi_size_t)expected_size - len)
                    {
                        free(buf);
                        return hpi_FALSE;
                    }
                    memcpy(buf + len, reader.data + reader.off, literal_len);
                    reader.off += literal_len;
                    len += literal_len;
                    is_have_data_back = hpi_TRUE;
                    continue;
                }
                dict_pos_back = 1u;
                reader.type_count = 0u;
                if (saved_len == 2u)
                {
                    continue;
                }
                if (saved_len == 3u)
                {
                    break;
                }
                free(buf);
                return hpi_FALSE;
            }
        }
        else
        {
            hpi_byte literal;
            if (len >= expected_size || !hpatch_ci_tuz_read_byte(&reader, &literal))
            {
                free(buf);
                return hpi_FALSE;
            }
            buf[len++] = literal;
            is_have_data_back = hpi_TRUE;
        }
    }

    if (len != expected_size)
    {
        free(buf);
        return hpi_FALSE;
    }
    /*
     * The TinyUZ end control realigns the type-bit reader. Reject any
     * remaining byte-stream data so mutated patches with recomputed outer
     * RBL CRC/size cannot be accepted by this production-path shim.
     */
    if (reader.off != reader.len || reader.type_count != 0u)
    {
        free(buf);
        return hpi_FALSE;
    }
    *output = buf;
    *output_len = len;
    return hpi_TRUE;
}

/**
 * @brief Restore a generic HPatchLite fixture body into a contiguous image.
 *
 * @param listener Listener context passed to production callbacks.
 * @param read_old Old-image read callback.
 * @param body     Uncompressed HPatchLite patch body.
 * @param len      Uncompressed patch body length.
 * @param new_size Expected restored new image size from the HPatch header.
 * @param output   Output restored new image.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_restore_body(hpatchi_listener_t *listener,
                                       hpi_TReadOld read_old,
                                       const hpi_byte *body,
                                       hpi_size_t len,
                                       uint32_t new_size,
                                       hpi_byte *output)
{
    hpi_size_t off = 0u;
    uint32_t cover_count = 0u;
    uint32_t new_pos_back = 0u;
    uint32_t old_pos_back = 0u;

    if (listener == NULL || read_old == NULL || body == NULL || output == NULL ||
        !hpatch_ci_read_var_uint(body, len, &off, 0u, hpi_TRUE, &cover_count) ||
        cover_count == 0u)
    {
        return hpi_FALSE;
    }

    for (uint32_t cover_index = 0u; cover_index < cover_count; cover_index++)
    {
        uint32_t cover_len = 0u;
        uint32_t old_pos_delta = 0u;
        uint32_t new_pos_delta = 0u;
        uint32_t cover_old_pos;
        uint32_t cover_new_pos;
        uint32_t diff_size;
        hpi_byte tag;
        hpi_BOOL copy_old_only;

        if (!hpatch_ci_read_var_uint(body, len, &off, 0u, hpi_TRUE, &cover_len) ||
            off >= len)
        {
            return hpi_FALSE;
        }

        tag = body[off++];
        copy_old_only = ((tag & 0x80u) != 0u) ? hpi_TRUE : hpi_FALSE;
        if (!hpatch_ci_read_var_uint(body, len, &off, (uint32_t)(tag & 0x1Fu),
                                     (tag & 0x20u) != 0u, &old_pos_delta) ||
            !hpatch_ci_read_var_uint(body, len, &off, 0u, hpi_TRUE,
                                     &new_pos_delta))
        {
            return hpi_FALSE;
        }

        if ((tag & 0x40u) != 0u)
        {
            if (old_pos_delta > old_pos_back)
            {
                return hpi_FALSE;
            }
            cover_old_pos = old_pos_back - old_pos_delta;
        }
        else
        {
            if (old_pos_delta > UINT32_MAX - old_pos_back)
            {
                return hpi_FALSE;
            }
            cover_old_pos = old_pos_back + old_pos_delta;
        }

        if (new_pos_delta > UINT32_MAX - new_pos_back)
        {
            return hpi_FALSE;
        }
        cover_new_pos = new_pos_back + new_pos_delta;
        if (cover_new_pos < new_pos_back || cover_new_pos > new_size ||
            cover_len > (new_size - cover_new_pos))
        {
            return hpi_FALSE;
        }

        diff_size = cover_new_pos - new_pos_back;
        if (diff_size > (len - off))
        {
            return hpi_FALSE;
        }
        memcpy(output + new_pos_back, body + off, diff_size);
        off += diff_size;

        if (cover_len != 0u)
        {
            if (cover_len > UINT32_MAX - cover_old_pos)
            {
                return hpi_FALSE;
            }
            if (!copy_old_only && cover_len > (len - off))
            {
                return hpi_FALSE;
            }
            for (uint32_t i = 0u; i < cover_len; i++)
            {
                hpi_byte old_byte;
                if (!read_old(listener, cover_old_pos + i, &old_byte, 1u))
                {
                    return hpi_FALSE;
                }
                output[cover_new_pos + i] = copy_old_only ? old_byte :
                    (hpi_byte)(old_byte + body[off + i]);
            }
            if (!copy_old_only)
            {
                off += cover_len;
            }
        }
        else if (cover_index != cover_count - 1u)
        {
            return hpi_FALSE;
        }

        new_pos_back = cover_new_pos + cover_len;
        old_pos_back = cover_old_pos + cover_len;
    }

    return (off == len && new_pos_back == new_size) ? hpi_TRUE : hpi_FALSE;
}

/**
 * @brief Decode an HPatchLite patch header and return an uncompressed body.
 *
 * @param patch    Full HPatchLite patch buffer.
 * @param len      Full HPatchLite patch length.
 * @param body     Output uncompressed body.
 * @param body_len Output uncompressed body length.
 * @param new_size Output expected new image size.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_decode_body(const hpi_byte *patch, hpi_size_t len,
                                      hpi_byte **body, hpi_size_t *body_len,
                                      uint32_t *new_size)
{
    hpi_size_t off = 4u;
    uint32_t uncompress_size = 0u;

    if (patch == NULL || body == NULL || body_len == NULL || new_size == NULL ||
        len < 4u || patch[0] != HPATCH_CI_MAGIC_H || patch[1] != HPATCH_CI_MAGIC_I ||
        (patch[3] >> 6u) != HPATCH_CI_VERSION ||
        !hpatch_ci_read_le_size(patch, len, &off, patch[3] & 7u, new_size) ||
        !hpatch_ci_read_le_size(patch, len, &off, (patch[3] >> 3u) & 7u,
                                &uncompress_size))
    {
        return hpi_FALSE;
    }

    if (patch[2] == HPATCH_CI_COMPRESS_NONE)
    {
        if (uncompress_size != 0u)
        {
            return hpi_FALSE;
        }
        *body_len = len - off;
        *body = (hpi_byte *)malloc(*body_len == 0u ? 1u : *body_len);
        if (*body == NULL)
        {
            return hpi_FALSE;
        }
        memcpy(*body, patch + off, *body_len);
        return hpi_TRUE;
    }
    if (patch[2] == HPATCH_CI_COMPRESS_TUZ && uncompress_size != 0u)
    {
        return hpatch_ci_tuz_decompress(patch + off, len - off, uncompress_size,
                                        body, body_len);
    }
    return hpi_FALSE;
}

hpi_patch_result_t hpi_patch(hpatchi_listener_t *listener,
                             int patch_cache_size,
                             int decompress_cache_size,
                             hpi_TInputStream_read read_diff,
                             hpi_TReadOld read_old,
                             hpi_TWriteNew write_new)
{
    hpi_byte *patch = NULL;
    hpi_byte *body = NULL;
    hpi_byte *output = NULL;
    hpi_size_t patch_len = 0u;
    hpi_size_t body_len = 0u;
    uint32_t new_size = 0u;
    hpi_patch_result_t result = HPATCHI_PATCH_ERROR;

    (void)patch_cache_size;
    (void)decompress_cache_size;

    if (listener == NULL || read_diff == NULL)
    {
        return HPATCHI_OPTIONS_ERROR;
    }
    if (read_old == NULL)
    {
        read_old = listener->read_old;
    }
    if (write_new == NULL)
    {
        write_new = listener->write_new;
    }
    if (read_old == NULL || write_new == NULL)
    {
        return HPATCHI_OPTIONS_ERROR;
    }

    if (!hpatch_ci_read_all(read_diff, (hpi_TInputStreamHandle)listener, &patch, &patch_len) ||
        !hpatch_ci_decode_body(patch, patch_len, &body, &body_len, &new_size))
    {
        goto cleanup;
    }
    output = (hpi_byte *)malloc(new_size == 0u ? 1u : new_size);
    if (output == NULL)
    {
        goto cleanup;
    }
    if (!hpatch_ci_restore_body(listener, read_old, body, body_len, new_size, output) ||
        !write_new(listener, output, new_size))
    {
        goto cleanup;
    }
    result = HPATCHI_SUCCESS;

cleanup:
    free(output);
    free(body);
    free(patch);
    return result;
}
