/**
 * @file hpatch_impl.c
 * @brief CI HPatchLite shim that exercises the production QBoot HPatch path.
 *
 * @details The shim implements the deterministic no-compress, single-cover
 * fixture subset generated by the QBoot package-tool tests. It is intentionally
 * small, but it runs through algorithm/qboot_hpatchlite.c instead of the host
 * adapter so CI cannot silently skip the production integration path.
 */
#include "hpatch_impl.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define HPATCH_CI_MAGIC_H       0x68u /**< HPatchLite 'h' magic byte. */
#define HPATCH_CI_MAGIC_I       0x49u /**< HPatchLite 'I' magic byte. */
#define HPATCH_CI_COMPRESS_NONE 0u    /**< No-compression fixture selector. */
#define HPATCH_CI_VERSION       1u    /**< Fixture format version. */
#define HPATCH_CI_READ_CHUNK    256u  /**< Patch stream read growth unit. */

/** @brief Parsed no-compress single-cover HPatchLite fixture plan. */
typedef struct
{
    uint32_t new_size;    /**< Expected restored new image size. */
    uint32_t diff_pos;    /**< Offset of literal diff bytes in patch buffer. */
    uint32_t diff_size;   /**< Literal diff bytes before the old-data cover. */
    uint32_t old_pos;     /**< Old image offset referenced by the cover. */
    uint32_t new_pos;     /**< New image offset where the cover is restored. */
    uint32_t cover_len;   /**< Number of bytes restored from old data. */
    uint32_t subdiff_pos; /**< Offset of cover sub-diff bytes in patch buffer. */
} hpatch_ci_plan_t;

/**
 * @brief Read the complete HPatchLite stream from the production callback.
 *
 * @param read_diff Stream read callback.
 * @param input_stream Stream callback context.
 * @param data         Output heap buffer containing the whole stream.
 * @param size      Output stream size in bytes.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_read_all(hpi_TInputStream_read read_diff,
                                   hpi_TInputStreamHandle input_stream,
                                   hpi_byte **data,
                                   hpi_size_t *size)
{
    hpi_byte *buf = NULL;
    hpi_size_t len = 0u;
    hpi_size_t cap = 0u;

    if (read_diff == NULL || data == NULL || size == NULL)
    {
        return hpi_FALSE;
    }

    for (;;)
    {
        hpi_size_t request = HPATCH_CI_READ_CHUNK;
        hpi_byte chunk[HPATCH_CI_READ_CHUNK];
        if (!read_diff(input_stream, chunk, &request))
        {
            free(buf);
            return hpi_FALSE;
        }
        if (request == 0u)
        {
            break;
        }
        if (len + request < len)
        {
            free(buf);
            return hpi_FALSE;
        }
        if (len + request > cap)
        {
            hpi_size_t next = cap == 0u ? HPATCH_CI_READ_CHUNK : cap;
            hpi_byte *new_buf;
            while (next < len + request)
            {
                if (next > ((hpi_size_t)-1) / 2u)
                {
                    free(buf);
                    return hpi_FALSE;
                }
                next *= 2u;
            }
            new_buf = (hpi_byte *)realloc(buf, next);
            if (new_buf == NULL)
            {
                free(buf);
                return hpi_FALSE;
            }
            buf = new_buf;
            cap = next;
        }
        memcpy(buf + len, chunk, request);
        len += request;
    }

    *data = buf;
    *size = len;
    return hpi_TRUE;
}

/**
 * @brief Read little-endian integer bytes from a patch buffer.
 *
 * @param data       Patch buffer.
 * @param len        Patch buffer length.
 * @param off        In/out read offset.
 * @param byte_count Number of little-endian bytes to consume.
 * @param out        Output integer value.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_read_le_size(const hpi_byte *data, hpi_size_t len,
                                       hpi_size_t *off, hpi_size_t byte_count,
                                       uint32_t *out)
{
    uint32_t value = 0u;

    if (data == NULL || off == NULL || out == NULL || byte_count > sizeof(uint32_t) ||
        *off > len || byte_count > (len - *off))
    {
        return hpi_FALSE;
    }
    for (hpi_size_t i = 0u; i < byte_count; i++)
    {
        value |= ((uint32_t)data[*off + i]) << (8u * i);
    }
    *off += byte_count;
    *out = value;
    return hpi_TRUE;
}

/**
 * @brief Read HPatchLite variable-length unsigned integer encoding.
 *
 * @param data     Patch buffer.
 * @param len      Patch buffer length.
 * @param off      In/out read offset.
 * @param initial  Initial low-bit value from the tag byte.
 * @param has_next Whether more bytes are present.
 * @param out      Output integer value.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_read_var_uint(const hpi_byte *data, hpi_size_t len,
                                        hpi_size_t *off, uint32_t initial,
                                        hpi_BOOL has_next, uint32_t *out)
{
    uint32_t value = initial;

    while (has_next)
    {
        hpi_byte code;
        if (data == NULL || off == NULL || out == NULL || *off >= len)
        {
            return hpi_FALSE;
        }
        code = data[*off];
        *off += 1u;
        value = (value << 7u) | (uint32_t)(code & 0x7Fu);
        has_next = (code >> 7u) != 0u ? hpi_TRUE : hpi_FALSE;
    }
    *out = value;
    return hpi_TRUE;
}

/**
 * @brief Parse the supported no-compress single-cover fixture subset.
 *
 * @param patch Patch buffer.
 * @param len   Patch buffer length.
 * @param plan  Output parsed restoration plan.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_parse_plan(const hpi_byte *patch, hpi_size_t len,
                                     hpatch_ci_plan_t *plan)
{
    hpi_size_t off = 4u;
    uint32_t uncompress_size = 0u;
    uint32_t cover_count = 0u;
    hpi_byte tag;
    hpi_BOOL copy_old_only;

    if (patch == NULL || plan == NULL || len < 4u ||
        patch[0] != HPATCH_CI_MAGIC_H || patch[1] != HPATCH_CI_MAGIC_I ||
        patch[2] != HPATCH_CI_COMPRESS_NONE || (patch[3] >> 6u) != HPATCH_CI_VERSION)
    {
        return hpi_FALSE;
    }
    memset(plan, 0, sizeof(*plan));
    if (!hpatch_ci_read_le_size(patch, len, &off, patch[3] & 7u, &plan->new_size) ||
        !hpatch_ci_read_le_size(patch, len, &off, (patch[3] >> 3u) & 7u,
                                &uncompress_size) ||
        uncompress_size != 0u ||
        !hpatch_ci_read_var_uint(patch, len, &off, 0u, hpi_TRUE, &cover_count) ||
        cover_count != 1u ||
        !hpatch_ci_read_var_uint(patch, len, &off, 0u, hpi_TRUE, &plan->cover_len) ||
        off >= len)
    {
        return hpi_FALSE;
    }

    tag = patch[off++];
    copy_old_only = ((tag & 0x80u) != 0u) ? hpi_TRUE : hpi_FALSE;
    if (!hpatch_ci_read_var_uint(patch, len, &off, (uint32_t)(tag & 0x1Fu),
                                 (tag & 0x20u) != 0u, &plan->old_pos) ||
        (tag & 0x40u) != 0u ||
        !hpatch_ci_read_var_uint(patch, len, &off, 0u, hpi_TRUE, &plan->new_pos) ||
        plan->new_pos > plan->new_size ||
        plan->cover_len > (plan->new_size - plan->new_pos) ||
        (plan->new_pos + plan->cover_len) != plan->new_size)
    {
        return hpi_FALSE;
    }

    plan->diff_size = plan->new_pos;
    plan->diff_pos = (uint32_t)off;
    if ((copy_old_only && plan->cover_len > 0u) || plan->diff_size > (len - off) ||
        plan->cover_len > (len - off - plan->diff_size))
    {
        return hpi_FALSE;
    }
    plan->subdiff_pos = plan->diff_pos + plan->diff_size;
    return ((hpi_size_t)plan->subdiff_pos + plan->cover_len == len) ? hpi_TRUE : hpi_FALSE;
}

/**
 * @brief Restore a parsed HPatchLite fixture into a contiguous new image.
 *
 * @param listener Listener context passed to the production callbacks.
 * @param read_old Old-image read callback.
 * @param patch    Patch buffer.
 * @param plan     Parsed patch plan.
 * @param output   Output restored new image.
 *
 * @return hpi_TRUE on success, hpi_FALSE otherwise.
 */
static hpi_BOOL hpatch_ci_restore_new(hpatchi_listener_t *listener,
                                      hpi_TReadOld read_old,
                                      const hpi_byte *patch,
                                      const hpatch_ci_plan_t *plan,
                                      hpi_byte *output)
{
    if (listener == NULL || read_old == NULL || patch == NULL || plan == NULL ||
        output == NULL)
    {
        return hpi_FALSE;
    }
    memcpy(output, patch + plan->diff_pos, plan->diff_size);
    for (uint32_t i = 0u; i < plan->cover_len; i++)
    {
        hpi_byte old_byte;
        if (!read_old(listener, plan->old_pos + i, &old_byte, 1u))
        {
            return hpi_FALSE;
        }
        output[plan->new_pos + i] = (hpi_byte)(old_byte + patch[plan->subdiff_pos + i]);
    }
    return hpi_TRUE;
}

hpi_patch_result_t hpi_patch(hpatchi_listener_t *listener,
                             int patch_cache_size,
                             int decompress_cache_size,
                             hpi_TInputStream_read read_diff,
                             hpi_TReadOld read_old,
                             hpi_TWriteNew write_new)
{
    hpi_byte *patch = NULL;
    hpi_byte *output = NULL;
    hpi_size_t patch_len = 0u;
    hpatch_ci_plan_t plan;
    hpi_patch_result_t result = HPATCHI_PATCH_ERROR;

    (void)patch_cache_size;
    (void)decompress_cache_size;

    if (listener == NULL || read_diff == NULL)
    {
        return HPATCHI_OPTIONS_ERROR;
    }
    if (read_old == NULL)
    {
        read_old = listener->read_old;
    }
    if (write_new == NULL)
    {
        write_new = listener->write_new;
    }
    if (read_old == NULL || write_new == NULL)
    {
        return HPATCHI_OPTIONS_ERROR;
    }

    if (!hpatch_ci_read_all(read_diff, (hpi_TInputStreamHandle)listener, &patch, &patch_len) ||
        !hpatch_ci_parse_plan(patch, patch_len, &plan))
    {
        goto cleanup;
    }
    output = (hpi_byte *)malloc(plan.new_size == 0u ? 1u : plan.new_size);
    if (output == NULL)
    {
        goto cleanup;
    }
    if (!hpatch_ci_restore_new(listener, read_old, patch, &plan, output) ||
        !write_new(listener, output, plan.new_size))
    {
        goto cleanup;
    }
    result = HPATCHI_SUCCESS;

cleanup:
    free(output);
    free(patch);
    return result;
}
