/* CI profile derived from the STM32F407 QBoot production configuration. */
#define RT_USING_DFS
#define DFS_USING_POSIX
#define DFS_USING_WORKDIR
#define DFS_FD_MAX 16
#define RT_USING_DFS_V1
#define DFS_FILESYSTEMS_MAX 4
#define DFS_FILESYSTEM_TYPES_MAX 4
#define RT_USING_DFS_DEVFS
#define RT_USING_DFS_ROMFS
#define RT_USING_DFS_ROMFS_USER_ROOT

/* FAL and STM32F407 flash integration. */
#define RT_USING_FAL
#define FAL_PART_HAS_TABLE_CFG
#define FAL_USING_SFUD_PORT
#define FAL_USING_NOR_FLASH_DEV_NAME "norflash0"
#define FAL_DEV_NAME_MAX 24
#define FAL_DEV_BLK_MAX 6
#define RT_USING_SPI
#define RT_USING_MTD_NOR
#define RT_USING_SFUD
#define RT_SFUD_USING_SFDP
#define RT_SFUD_USING_FLASH_INFO_TABLE
#define RT_SFUD_SPI_MAX_HZ 50000000
#define BSP_USING_FS
#define BSP_USING_SPI_FLASH_LITTLEFS
#define BSP_USING_SPI_FLASH
#define BSP_USING_SPI
#define BSP_USING_SPI1
#define BSP_USING_ON_CHIP_FLASH

#define PKG_USING_CRCLIB
#define CRCLIB_USING_CRC8
#define CRC8_USING_CONST_TABLE
#define CRC8_POLY_8C
#define CRC8_POLY 140
#define CRCLIB_USING_CRC16
#define CRC16_USING_CONST_TABLE
#define CRC16_POLY_A001
#define CRC16_POLY 40961
#define CRCLIB_USING_CRC32
#define CRC32_USING_CONST_TABLE
#define CRC32_POLY_EDB88320
#define CRC32_POLY 3988292384
#define PKG_USING_CRCLIB_V102

#define PKG_USING_QBOOT
#define QBOOT_PKG_SOURCE_FAL
#define QBOOT_PKG_SOURCE_FS
#define QBOOT_APP_STORE_FAL
#define QBOOT_APP_FAL_PART_NAME "app"
#define QBOOT_DOWNLOAD_STORE_FS
#define QBOOT_DOWNLOAD_FILE_PATH "/flash/download.rbl"
#define QBOOT_DOWNLOAD_SIGN_FILE_PATH "/flash/download.rbl.sign"
#define QBOOT_FACTORY_STORE_FS
#define QBOOT_FACTORY_FILE_PATH "/flash/factory.rbl"
#define QBOOT_USING_SHELL
#define QBOOT_SHELL_KEY_CHK_TMO 1
#define QBOOT_SHELL_CMD_REASON
#define QBOOT_USING_UPDATE_MGR
#define QBOOT_POLL_DELAY_MS 20
#define QBT_UPDATE_MGR_PROGRESS_ENABLE
#define QBT_UPDATE_MGR_PROGRESS_PRINT_ENABLE
#define QBOOT_UPDATE_MGR_USE_DOWNLOAD_HELPER
#define QBOOT_USING_STATUS_LED
#define QBOOT_STATUS_LED_PIN 35
#define QBOOT_STATUS_LED_LEVEL 0
#define QBOOT_THREAD_STACK_SIZE 4096
#define QBOOT_THREAD_PRIO 5
#define PKG_USING_QBOOT_LATEST_VERSION

#define PKG_USING_QLED
#define QLED_TOTAL 5
#define QLED_TIME_UNIT_MS 10
#define QLED_THREAD_NAME "qled"
#define QLED_THREAD_STACK_SIZE 512
#define QLED_THREAD_PRIO 3
#define PKG_USING_QLED_LATEST_VERSION

/* Exercise the filesystem provider used by the reference configuration. */
#define PKG_USING_LITTLEFS
#define PKG_USING_LITTLEFS_LATEST_VERSION
#define LFS_READ_SIZE 256
#define LFS_PROG_SIZE 256
#define LFS_BLOCK_SIZE 4096
#define LFS_NO_DEBUG
#define LFS_CACHE_SIZE 256
#define LFS_BLOCK_CYCLES 500
#define LFS_THREADSAFE
#define LFS_LOOKAHEAD_MAX 128
#define RT_DEF_LFS_DRIVERS 1
