/* CI-only HPatchLite filesystem swap profile using CUSTOM storage for app data. */
#define RT_USING_DFS
#define DFS_USING_POSIX
#define DFS_USING_WORKDIR
#define DFS_FD_MAX               16
#define RT_USING_DFS_V1
#define DFS_FILESYSTEMS_MAX      4
#define DFS_FILESYSTEM_TYPES_MAX 4
#define RT_USING_DFS_DEVFS
#define RT_USING_DFS_ROMFS

#define QBOOT_PKG_SOURCE_CUSTOM
#define QBOOT_PKG_SOURCE_FS
#define QBOOT_APP_STORE_CUSTOM
#define QBOOT_APP_FLASH_ADDR       0x08040000
#define QBOOT_APP_FLASH_LEN        0x00040000
#define QBOOT_DOWNLOAD_STORE_CUSTOM
#define QBOOT_DOWNLOAD_FLASH_ADDR  0x08080000
#define QBOOT_DOWNLOAD_FLASH_LEN   0x00040000
#define QBOOT_FACTORY_STORE_CUSTOM
#define QBOOT_FACTORY_FLASH_ADDR   0x080C0000
#define QBOOT_FACTORY_FLASH_LEN    0x00020000
#define QBOOT_FLASH_ERASE_ALIGN    4096
#define PKG_USING_HPATCHLITE
#define QBOOT_USING_HPATCHLITE
#define QBOOT_HPATCH_PATCH_CACHE_SIZE      4096
#define QBOOT_HPATCH_DECOMPRESS_CACHE_SIZE 4096
#define QBOOT_HPATCH_USE_STORAGE_SWAP
#define QBOOT_HPATCH_SWAP_STORE_FS
#define QBOOT_HPATCH_SWAP_PART_NAME        "swap"
#define QBOOT_HPATCH_SWAP_FILE_PATH        "/hpatch.swap"
#define QBOOT_HPATCH_SWAP_FILE_SIZE        131072
#define QBOOT_HPATCH_SWAP_OFFSET           0
#define QBOOT_HPATCH_COPY_BUFFER_SIZE      4096
