/* CI-only HPatchLite FAL swap profile using CUSTOM storage for app data. */
#define RT_USING_FAL
#define FAL_PART_HAS_TABLE_CFG
#define FAL_DEV_NAME_MAX       24
#define FAL_DEV_BLK_MAX        6
#define BSP_USING_ON_CHIP_FLASH

#define QBOOT_PKG_SOURCE_CUSTOM
#define QBOOT_PKG_SOURCE_FAL
#define QBOOT_APP_STORE_CUSTOM
#define QBOOT_APP_FLASH_ADDR       0x08040000
#define QBOOT_APP_FLASH_LEN        0x00040000
#define QBOOT_DOWNLOAD_STORE_CUSTOM
#define QBOOT_DOWNLOAD_FLASH_ADDR  0x08080000
#define QBOOT_DOWNLOAD_FLASH_LEN   0x00040000
#define QBOOT_FACTORY_STORE_CUSTOM
#define QBOOT_FACTORY_FLASH_ADDR   0x080C0000
#define QBOOT_FACTORY_FLASH_LEN    0x00020000
#define QBOOT_FLASH_ERASE_ALIGN    4096
#define PKG_USING_HPATCHLITE
#define QBOOT_USING_HPATCHLITE
#define QBOOT_HPATCH_PATCH_CACHE_SIZE      4096
#define QBOOT_HPATCH_DECOMPRESS_CACHE_SIZE 4096
#define QBOOT_HPATCH_USE_STORAGE_SWAP
#define QBOOT_HPATCH_SWAP_STORE_FAL
#define QBOOT_HPATCH_SWAP_PART_NAME        "swap"
#define QBOOT_HPATCH_SWAP_OFFSET           0
#define QBOOT_HPATCH_COPY_BUFFER_SIZE      4096
