/* CI-only update manager profile using the CUSTOM backend. */
#define QBOOT_PKG_SOURCE_CUSTOM
#define QBOOT_APP_STORE_CUSTOM
#define QBOOT_APP_FLASH_ADDR       0x08040000
#define QBOOT_APP_FLASH_LEN        0x00040000
#define QBOOT_DOWNLOAD_STORE_CUSTOM
#define QBOOT_DOWNLOAD_FLASH_ADDR  0x08080000
#define QBOOT_DOWNLOAD_FLASH_LEN   0x00040000
#define QBOOT_FACTORY_STORE_CUSTOM
#define QBOOT_FACTORY_FLASH_ADDR   0x080C0000
#define QBOOT_FACTORY_FLASH_LEN    0x00020000
#define QBOOT_FLASH_ERASE_ALIGN    4096
#define QBOOT_USING_UPDATE_MGR
#define QBOOT_POLL_DELAY_MS        20
#define QBT_UPDATE_MGR_PROGRESS_ENABLE
#define QBT_UPDATE_MGR_PROGRESS_PRINT_ENABLE
#define QBOOT_UPDATE_MGR_USE_DOWNLOAD_HELPER

#define QBOOT_SHELL_KEY_CHK_TMO   1
