/* CI-only AES/GZIP/QUICKLZ/FASTLZ profile using the CUSTOM backend. */
#define QBOOT_PKG_SOURCE_CUSTOM
#define QBOOT_APP_STORE_CUSTOM
#define QBOOT_APP_FLASH_ADDR       0x08040000
#define QBOOT_APP_FLASH_LEN        0x00040000
#define QBOOT_DOWNLOAD_STORE_CUSTOM
#define QBOOT_DOWNLOAD_FLASH_ADDR  0x08080000
#define QBOOT_DOWNLOAD_FLASH_LEN   0x00040000
#define QBOOT_FACTORY_STORE_CUSTOM
#define QBOOT_FACTORY_FLASH_ADDR   0x080C0000
#define QBOOT_FACTORY_FLASH_LEN    0x00020000
#define QBOOT_FLASH_ERASE_ALIGN    4096
#define PKG_USING_TINYCRYPT
#define TINY_CRYPT_AES
#define PKG_USING_ZLIB
#define PKG_USING_QUICKLZ
#define PKG_USING_FASTLZ
#define QBOOT_USING_AES
#define QBOOT_AES_IV              "0123456789ABCDEF"
#define QBOOT_AES_KEY             "0123456789ABCDEF0123456789ABCDEF"
#define QBOOT_USING_GZIP
#define QBOOT_USING_QUICKLZ
#define QBOOT_USING_FASTLZ
